version: '3.8'

services:
  # Solr service (existing)
  solr:
    image: solr:9.2
    container_name: asra_solr
    ports:
      - "8983:8983"
    volumes:
      - ./docker/solr/configsets:/configsets
      - solr_data:/var/solr
    command:
      - solr-precreate
      - documents
      - /configsets/documents
    networks:
      - asra-network

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: asra_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - asra-network

  # Ollama for embeddings generation
  ollama:
    image: ollama/ollama:latest
    container_name: asra_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - asra-network

  # API server
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: asra_api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - ./docker/qdrant:/app/scripts/qdrant
    depends_on:
      - solr
      - qdrant
      - ollama
    networks:
      - asra-network
    environment:
      - SOLR_ENDPOINT=http://solr:8983/solr/documents
      - QDRANT_ENDPOINT=http://qdrant:6333
      - OLLAMA_ENDPOINT=http://ollama:11434

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asra_frontend
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - api
      - solr
    networks:
      - asra-network

networks:
  asra-network:
    driver: bridge

volumes:
  solr_data:
  qdrant_data:
  ollama_data:
