services:
  # Solr service (existing)
  solr:
    image: solr:latest
    container_name: asra_solr
    ports:
      - "8983:8983"
    volumes:
      - ../search-engines/solr/configsets:/configsets
      - solr_data:/var/solr
    command:
      - solr-precreate
      - documents
      - /configsets/documents
    networks:
      - asra-network

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: asra_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - asra-network

  # Ollama for embeddings generation
  ollama:
    build: 
      context: .
      dockerfile: Dockerfile.ollama
    container_name: asra_ollama
    #devices:
    #  - /dev/kfd:/dev/kfd
    #  - /dev/dri:/dev/dri
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - asra-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API server
  api:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile.api
    container_name: asra_api
    ports:
      - "3001:3001"
    volumes:
      # Nur Quellcode mounten, nicht den ganzen Ordner, um node_modules zu erhalten
      - ../backend/api/routes:/app/routes
      - ../backend/api/server.js:/app/server.js
      - ../search-engines/qdrant:/app/scripts/qdrant
    depends_on:
      - solr
      - qdrant
      - ollama
    networks:
      - asra-network
    environment:
      - SOLR_ENDPOINT=http://solr:8983/solr/documents
      - QDRANT_ENDPOINT=http://qdrant:6333
      - OLLAMA_ENDPOINT=http://ollama:11434

  # Frontend
  frontend:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    container_name: asra_frontend
    ports:
      - "8080:80"
    depends_on:
      - api
      - solr
    networks:
      - asra-network

  # OpenWebUI for Ollama
  openwebui:
    image: ghcr.io/open-webui/open-webui
    container_name: asra_openwebui
    ports:
      - "8181:8080"  # Nota: Verwendung von Port 8181, um Konflikte mit Frontend-Port 8080 zu vermeiden
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - openwebui_data:/app/backend/data:rw
    depends_on:
      - ollama
    networks:
      - asra-network
    restart: unless-stopped

networks:
  asra-network:
    driver: bridge

volumes:
  solr_data:
  qdrant_data:
  ollama_data:
  openwebui_data:
